import {test} from 'node:test';
import assert from 'node:assert/strict';
import {id as hashEvent} from 'quais';
import {createApp,ADMIN} from '../server.mjs';
import {saveProfile,readCategories} from '../profiles.mjs';
import {createQuestion,replyToThread,previewQuestion,readThread} from '../threads.mjs';
import {library,reportContent,adminReports} from '../member-tools.mjs';
import {acceptAnswer} from '../lifecycle.mjs';
import {createRewardConfirmation} from '../reward-confirmation.mjs';
import {REWARD_ADDRESS,transferData} from '../payments.mjs';
import {NS_TOKEN} from '../neuron-token.mjs';
import {listNotifications,readNotifications} from '../notifications.mjs';
function fixture(t){const {db}=createApp({database:':memory:'});t.after(()=>db.close());const now=Date.now(),accounts=[ADMIN,'0x00'+'2'.repeat(38),'0x00'+'3'.repeat(38),'0x00'+'4'.repeat(38)].map((address,i)=>({address,role:i?'member':'admin'}));
 accounts.forEach((a,i)=>{db.prepare('INSERT INTO accounts VALUES(?,?)').run(a.address,now);saveProfile(db,a.address,{nickname:'Member '+i,work:[i===3?'Other':'Driving'],hobbies:i===3?[]:['Travel']},now);});
 const ids=readCategories(db).work.filter(c=>c.name==='Driving').map(c=>c.id).concat(readCategories(db).hobbies.map(c=>c.id)),q=createQuestion(db,accounts[0],{categoryIds:ids,body:'Where should I travel?'},now).id;replyToThread(db,accounts[1],q,{body:'Visit the coast.'},now+1);const reply=readThread(db,accounts[0],q).replies[0];return {db,now,accounts,ids,q,reply};}
test('topic counts count profile members and preview deduplicates both groups without creating a question',t=>{const f=fixture(t),before=f.db.prepare('SELECT count(*) AS n FROM questions').get().n;
 const cat=readCategories(f.db);assert.equal(cat.work.find(c=>c.name==='Driving').memberCount,3);assert.equal(cat.hobbies[0].memberCount,3);
 const p=previewQuestion(f.db,f.accounts[0],{categoryIds:[...f.ids,...f.ids],body:'Preview'});assert.equal(p.recipientCount,2);assert.equal(p.categoryIds.length,2);assert.equal(f.db.prepare('SELECT count(*) AS n FROM questions').get().n,before);assert.equal(JSON.stringify(p).includes(f.accounts[1].address),false);
 assert.throws(()=>previewQuestion(f.db,null,{categoryIds:f.ids,body:'x'}));});
test('saved answers are private, version-checked copies surviving edits and closure',t=>{const {db,accounts,q,reply,now}=fixture(t);const save={action:'save',replyId:reply.id,version:1};
 assert.throws(()=>library(db,accounts[3],save),e=>e.status===404);assert.throws(()=>library(db,accounts[0],{...save,version:99}),e=>e.status===409);
 library(db,accounts[0],save);library(db,accounts[0],save);assert.equal(library(db,accounts[0],null).total,1);assert.equal(library(db,accounts[2],null).total,0);
 db.prepare('UPDATE replies SET body=?,version=2 WHERE id=?').run('Changed answer',reply.id);acceptAnswer(db,accounts[0],q,{replyId:reply.id,version:2},now+10);
 assert.equal(library(db,accounts[0],null).items[0].answer,'Visit the coast.');assert.throws(()=>library(db,accounts[2],{...save,version:2}),e=>e.status===404);
 library(db,accounts[2],{action:'remove',replyId:reply.id});assert.equal(library(db,accounts[0],null).total,1);library(db,accounts[0],{action:'remove',replyId:reply.id});assert.equal(library(db,accounts[0],null).total,0);
});
test('reports require conversation access, retain snapshots and deduplicate; review is admin-only',t=>{const {db,accounts,q,reply}=fixture(t),input={questionId:q,replyId:reply.id,reason:'spam',details:'Repeated promotion'};
 assert.throws(()=>reportContent(db,accounts[3],input),e=>e.status===404);reportContent(db,accounts[2],input);reportContent(db,accounts[2],input);
 assert.throws(()=>adminReports(db,accounts[2],null,new URLSearchParams()),e=>e.status===403);const data=adminReports(db,accounts[0],null,new URLSearchParams());assert.equal(data.total,1);assert.equal(data.items[0].answer,'Visit the coast.');adminReports(db,accounts[0],{id:data.items[0].id});assert.ok(adminReports(db,accounts[0],null,new URLSearchParams()).items[0].resolvedAt);
});
test('verified reward notifies only its winner after 3 confirmations and cannot be replayed',async t=>{const {db,accounts,q,reply,now}=fixture(t);acceptAnswer(db,accounts[0],q,{replyId:reply.id,version:1},now+10);
 const hash='0x'+'a'.repeat(64),blockHash='0x'+'b'.repeat(64),units='10000000000000000000',recipient=accounts[1].address;
 const tx={hash,from:REWARD_ADDRESS,to:NS_TOKEN.address,input:transferData(recipient,units),value:'0x0',blockHash};
 const receipt={transactionHash:hash,status:'0x1',blockNumber:'0x64',blockHash,logs:[{address:NS_TOKEN.address,topics:[hashEvent('Transfer(address,address,uint256)'),'0x'+REWARD_ADDRESS.slice(2).toLowerCase().padStart(64,'0'),'0x'+recipient.slice(2).padStart(64,'0')],data:'0x'+BigInt(units).toString(16).padStart(64,'0')}]};
 const canonicalBlock={hash:blockHash,timestamp:'0x'+Math.ceil((now+1000)/1000).toString(16)};let head='0x65';const confirm=createRewardConfirmation(db,async(url,options)=>{const {method}=JSON.parse(options.body);return {ok:true,json:async()=>({result:method==='quai_chainId'?'0x9':method==='quai_blockNumber'?head:method==='quai_getTransactionReceipt'?receipt:method==='quai_getTransactionByHash'?tx:canonicalBlock})};});
 const input={questionId:q,txHash:hash};await assert.rejects(confirm(accounts[2],input),e=>e.status===403);await assert.rejects(confirm(accounts[0],input),e=>e.status===409);head='0x66';
 receipt.status='0x0';await assert.rejects(confirm(accounts[0],input),e=>e.status===400);receipt.status='0x1';
 const originalAddress=receipt.logs[0].address;receipt.logs[0].address=accounts[2].address;await assert.rejects(confirm(accounts[0],input),e=>e.status===400);receipt.logs[0].address=originalAddress;
 canonicalBlock.hash='0x'+'c'.repeat(64);await assert.rejects(confirm(accounts[0],input),e=>e.status===400);canonicalBlock.hash=blockHash;
 const originalTime=canonicalBlock.timestamp;canonicalBlock.timestamp='0x1';await assert.rejects(confirm(accounts[0],input),e=>e.status===400);canonicalBlock.timestamp=originalTime;
 tx.from=accounts[2].address;await assert.rejects(confirm(accounts[0],input),e=>e.status===400);tx.from=REWARD_ADDRESS;
 assert.equal((await confirm(accounts[0],input)).amount,'10');await confirm(accounts[0],input);
 const n=listNotifications(db,accounts[1],new URLSearchParams());assert.equal(n.total,1);assert.equal(n.notifications[0].kind,'reward');assert.equal(n.notifications[0].amount,'10');assert.equal(n.unread,1);assert.equal(listNotifications(db,accounts[2],new URLSearchParams()).total,0);
 assert.throws(()=>readNotifications(db,accounts[2],{id:n.notifications[0].id},false,now),e=>e.status===404);
 readNotifications(db,accounts[1],{throughId:n.throughId,throughRewardId:n.throughRewardId},true,now);assert.equal(listNotifications(db,accounts[1],new URLSearchParams()).unread,0);assert.equal(db.prepare('SELECT count(*) AS n FROM reward_receipts').get().n,1);
});
