-- Fresh PostgreSQL schema. Existing SQLite files are deliberately left untouched.
CREATE TABLE accounts(address TEXT PRIMARY KEY, created_at BIGINT NOT NULL);

CREATE TABLE challenges(id TEXT PRIMARY KEY, browser_hash TEXT NOT NULL, address TEXT NOT NULL, message TEXT NOT NULL, expires BIGINT NOT NULL, legal_hash TEXT);

CREATE TABLE sessions(token_hash TEXT PRIMARY KEY, address TEXT NOT NULL REFERENCES accounts(address), expires BIGINT NOT NULL);

CREATE INDEX sessions_expiry ON sessions(expires);

CREATE INDEX challenges_expiry ON challenges(expires);

CREATE TABLE legal_documents(hash TEXT PRIMARY KEY, version TEXT NOT NULL, terms TEXT NOT NULL, privacy TEXT NOT NULL);

CREATE TABLE legal_acceptances(address TEXT NOT NULL REFERENCES accounts(address), document_hash TEXT NOT NULL REFERENCES legal_documents(hash), accepted_at BIGINT NOT NULL, message TEXT NOT NULL, signature TEXT NOT NULL, PRIMARY KEY(address,document_hash));

CREATE TABLE profiles(
    address TEXT PRIMARY KEY REFERENCES accounts(address), nickname TEXT NOT NULL,
    first_name TEXT NOT NULL DEFAULT '', last_name TEXT NOT NULL DEFAULT '', updated_at BIGINT NOT NULL);

CREATE TABLE categories(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, kind TEXT NOT NULL CHECK(kind IN ('work','hobbies')),
      name TEXT NOT NULL, normalized_name TEXT NOT NULL, UNIQUE(kind, normalized_name));

CREATE TABLE profile_categories(
      address TEXT NOT NULL REFERENCES profiles(address) ON DELETE CASCADE,
      category_id BIGINT NOT NULL REFERENCES categories(id), PRIMARY KEY(address, category_id));

CREATE TABLE questions(id TEXT PRIMARY KEY, author TEXT NOT NULL REFERENCES profiles(address),category_id BIGINT NOT NULL REFERENCES categories(id),body TEXT NOT NULL,created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL,revision BIGINT NOT NULL DEFAULT 1, deleted_at BIGINT, closed_at BIGINT);

CREATE TABLE question_participants(question_id TEXT NOT NULL REFERENCES questions(id),address TEXT NOT NULL REFERENCES accounts(address),is_recipient BIGINT NOT NULL,PRIMARY KEY(question_id,address));

CREATE INDEX participants_address ON question_participants(address,question_id);

CREATE TABLE replies(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,question_id TEXT NOT NULL REFERENCES questions(id),author TEXT NOT NULL REFERENCES profiles(address),body TEXT NOT NULL,created_at BIGINT NOT NULL, posted_revision BIGINT, deleted_at BIGINT, edited_at BIGINT, version BIGINT NOT NULL DEFAULT 1);

CREATE INDEX replies_question ON replies(question_id,id);

CREATE TABLE question_reads(question_id TEXT NOT NULL REFERENCES questions(id),address TEXT NOT NULL REFERENCES accounts(address),revision BIGINT NOT NULL,PRIMARY KEY(question_id,address));

CREATE TABLE answer_slots(question_id TEXT NOT NULL REFERENCES questions(id),author TEXT NOT NULL REFERENCES accounts(address),PRIMARY KEY(question_id,author));

CREATE TABLE question_categories(question_id TEXT NOT NULL REFERENCES questions(id),category_id BIGINT NOT NULL REFERENCES categories(id),PRIMARY KEY(question_id,category_id));

CREATE TABLE reply_votes(reply_id BIGINT NOT NULL REFERENCES replies(id),voter TEXT NOT NULL REFERENCES accounts(address),value BIGINT NOT NULL CHECK(value IN (-1,1)), awarded_at BIGINT NOT NULL DEFAULT 0,PRIMARY KEY(reply_id,voter));

CREATE TABLE admin_audit(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,question_id TEXT NOT NULL REFERENCES questions(id),actor TEXT NOT NULL REFERENCES accounts(address),action TEXT NOT NULL CHECK(action IN ('delete','restore')),created_at BIGINT NOT NULL);

CREATE INDEX audit_question ON admin_audit(question_id,id);

CREATE INDEX questions_deleted ON questions(deleted_at);

CREATE TABLE notifications(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,address TEXT NOT NULL REFERENCES accounts(address),question_id TEXT NOT NULL REFERENCES questions(id),actor TEXT NOT NULL REFERENCES accounts(address),kind TEXT NOT NULL CHECK(kind IN ('question','reply')),revision BIGINT NOT NULL,created_at BIGINT NOT NULL,read_at BIGINT,UNIQUE(address,question_id,revision));

CREATE INDEX notifications_address ON notifications(address,id);

CREATE INDEX questions_expiry ON questions(closed_at,created_at);

CREATE TABLE accepted_answers(question_id TEXT PRIMARY KEY REFERENCES questions(id),reply_id BIGINT,question_body TEXT NOT NULL,answer_body TEXT,question_author TEXT NOT NULL,answer_author TEXT,question_nickname TEXT NOT NULL,answer_nickname TEXT,upvotes BIGINT NOT NULL,selection TEXT NOT NULL CHECK(selection IN ('author','automatic','unanswered')),closed_at BIGINT NOT NULL);

CREATE TABLE blocked_members(id TEXT PRIMARY KEY,owner TEXT NOT NULL REFERENCES accounts(address),target TEXT NOT NULL REFERENCES accounts(address),UNIQUE(owner,target));

CREATE TABLE deadline_reminders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,address TEXT NOT NULL REFERENCES accounts(address),question_id TEXT UNIQUE NOT NULL REFERENCES questions(id),created_at BIGINT NOT NULL,read_at BIGINT);

CREATE TABLE conversation_archive(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,event TEXT NOT NULL,question_id TEXT NOT NULL,
 reply_id BIGINT,event_at BIGINT NOT NULL,payload TEXT NOT NULL);

CREATE TABLE archive_meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);

CREATE TABLE saved_answers(owner TEXT NOT NULL,reply_id BIGINT NOT NULL,question_id TEXT NOT NULL,question TEXT NOT NULL,answer TEXT NOT NULL,author TEXT NOT NULL,version BIGINT NOT NULL,saved_at BIGINT NOT NULL,PRIMARY KEY(owner,reply_id));

CREATE TABLE content_reports(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,reporter TEXT NOT NULL,question_id TEXT NOT NULL,reply_id BIGINT NOT NULL DEFAULT 0,reason TEXT NOT NULL,details TEXT NOT NULL,snapshot TEXT NOT NULL,created_at BIGINT NOT NULL,resolved_at BIGINT,UNIQUE(reporter,question_id,reply_id));

CREATE TABLE reward_receipts(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,question_id TEXT UNIQUE NOT NULL,recipient TEXT NOT NULL,units TEXT NOT NULL,tx_hash TEXT UNIQUE NOT NULL,created_at BIGINT NOT NULL,read_at BIGINT);

CREATE TABLE signed_actions(id TEXT PRIMARY KEY,address TEXT NOT NULL,session_hash TEXT NOT NULL,path TEXT NOT NULL,payload TEXT NOT NULL,message TEXT NOT NULL,expires BIGINT NOT NULL,result TEXT,completed BIGINT);

CREATE INDEX signed_actions_recent ON signed_actions(address,path,completed);

CREATE TABLE debate_messages(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,question_id TEXT NOT NULL REFERENCES questions(id),author TEXT NOT NULL REFERENCES profiles(address),body TEXT NOT NULL,client_id TEXT NOT NULL,created_at BIGINT NOT NULL,UNIQUE(question_id,author,client_id));

CREATE INDEX debate_thread ON debate_messages(question_id,id);

CREATE TABLE debate_presence(question_id TEXT NOT NULL REFERENCES questions(id),address TEXT NOT NULL REFERENCES profiles(address),session_hash TEXT NOT NULL,seen BIGINT NOT NULL,PRIMARY KEY(question_id,address,session_hash));

CREATE TABLE payment_intents(id TEXT PRIMARY KEY,payer TEXT NOT NULL,reply_id BIGINT NOT NULL REFERENCES replies(id),action TEXT NOT NULL,recipient TEXT NOT NULL,units TEXT NOT NULL,body TEXT NOT NULL,reply_version BIGINT NOT NULL,start_block TEXT NOT NULL,created_at BIGINT NOT NULL,tx_hash TEXT UNIQUE,completed_at BIGINT);

CREATE INDEX payment_owner ON payment_intents(payer,completed_at);

CREATE TABLE site_visitors(week BIGINT NOT NULL,visitor TEXT NOT NULL,PRIMARY KEY(week,visitor));

CREATE TABLE site_presence(visitor TEXT PRIMARY KEY,address TEXT,seen BIGINT NOT NULL);

CREATE TABLE globe_preferences(address TEXT PRIMARY KEY REFERENCES accounts(address),enabled BIGINT NOT NULL CHECK(enabled IN(0,1)));

CREATE TABLE globe_presence(address TEXT PRIMARY KEY REFERENCES accounts(address),country TEXT NOT NULL,seen BIGINT NOT NULL);

CREATE TABLE token_confirmations(address TEXT PRIMARY KEY REFERENCES accounts(address), contract TEXT NOT NULL, confirmed_at BIGINT NOT NULL);

CREATE TABLE reward_baselines(week BIGINT PRIMARY KEY,balance TEXT NOT NULL,observed_at BIGINT NOT NULL);
CREATE TABLE used_transactions(chain_id BIGINT NOT NULL,tx_hash TEXT NOT NULL,kind TEXT NOT NULL CHECK(kind IN ('payment','reward')),reference TEXT NOT NULL,PRIMARY KEY(chain_id,tx_hash));

CREATE INDEX profile_categories_topic ON profile_categories(category_id,address);
CREATE INDEX question_categories_topic ON question_categories(category_id,question_id);
CREATE INDEX questions_author ON questions(author,updated_at);
CREATE INDEX reply_votes_week ON reply_votes(awarded_at,reply_id) WHERE value=1;
CREATE INDEX replies_author ON replies(author,created_at);
CREATE INDEX payment_reply ON payment_intents(reply_id) WHERE completed_at IS NOT NULL;
CREATE INDEX rewards_recipient ON reward_receipts(recipient,id);
CREATE INDEX blocked_target ON blocked_members(target,owner);

CREATE FUNCTION archive_questions_change() RETURNS trigger LANGUAGE plpgsql AS $$
 DECLARE row_value questions%ROWTYPE; event_name TEXT;
 BEGIN
   IF TG_OP = 'UPDATE' AND OLD.body IS NOT DISTINCT FROM NEW.body AND OLD.deleted_at IS NOT DISTINCT FROM NEW.deleted_at AND OLD.closed_at IS NOT DISTINCT FROM NEW.closed_at THEN RETURN NEW; END IF;
   IF TG_OP = 'DELETE' THEN row_value := OLD; event_name := 'QUESTION REMOVED';
   ELSE row_value := NEW;
     IF TG_OP = 'INSERT' THEN event_name := 'QUESTION CREATED';
     ELSIF NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL THEN event_name := 'QUESTION DELETED';
     ELSIF NEW.deleted_at IS NULL AND OLD.deleted_at IS NOT NULL THEN event_name := 'QUESTION RESTORED';
     ELSIF NEW.closed_at IS NOT NULL AND OLD.closed_at IS NULL THEN event_name := 'QUESTION CLOSED';
     ELSE event_name := 'QUESTION EDITED'; END IF;
   END IF;
   INSERT INTO conversation_archive(event,question_id,reply_id,event_at,payload) VALUES(event_name,row_value.id,NULL,CASE WHEN TG_OP='INSERT' THEN row_value.created_at ELSE floor(extract(epoch FROM clock_timestamp())*1000)::BIGINT END,
   json_build_object('author',row_value.author,'nickname',COALESCE((SELECT nickname FROM profiles WHERE address=row_value.author),''),'body',row_value.body,'createdAt',row_value.created_at,'version',1,'deletedAt',row_value.deleted_at,'closedAt',row_value.closed_at)::TEXT);
   RETURN row_value;
 END; $$;
 CREATE TRIGGER archive_questions AFTER INSERT OR UPDATE OR DELETE ON questions FOR EACH ROW EXECUTE FUNCTION archive_questions_change();

CREATE FUNCTION archive_replies_change() RETURNS trigger LANGUAGE plpgsql AS $$
 DECLARE row_value replies%ROWTYPE; event_name TEXT;
 BEGIN
   IF TG_OP = 'UPDATE' AND OLD.body IS NOT DISTINCT FROM NEW.body AND OLD.deleted_at IS NOT DISTINCT FROM NEW.deleted_at AND OLD.version IS NOT DISTINCT FROM NEW.version THEN RETURN NEW; END IF;
   IF TG_OP = 'DELETE' THEN row_value := OLD; event_name := 'ANSWER REMOVED';
   ELSE row_value := NEW;
     IF TG_OP = 'INSERT' THEN event_name := 'ANSWER CREATED';
     ELSIF NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL THEN event_name := 'ANSWER DELETED';
     ELSIF NEW.deleted_at IS NULL AND OLD.deleted_at IS NOT NULL THEN event_name := 'ANSWER RESTORED';
     
     ELSE event_name := 'ANSWER EDITED'; END IF;
   END IF;
   INSERT INTO conversation_archive(event,question_id,reply_id,event_at,payload) VALUES(event_name,row_value.question_id,row_value.id,CASE WHEN TG_OP='INSERT' THEN row_value.created_at ELSE floor(extract(epoch FROM clock_timestamp())*1000)::BIGINT END,
   json_build_object('author',row_value.author,'nickname',COALESCE((SELECT nickname FROM profiles WHERE address=row_value.author),''),'body',row_value.body,'createdAt',row_value.created_at,'version',row_value.version,'deletedAt',row_value.deleted_at,'closedAt',NULL)::TEXT);
   RETURN row_value;
 END; $$;
 CREATE TRIGGER archive_replies AFTER INSERT OR UPDATE OR DELETE ON replies FOR EACH ROW EXECUTE FUNCTION archive_replies_change();
