-- Additive reputation ledger. All points are integer hundredths.
CREATE TABLE weekly_rounds (
 round_id BIGINT PRIMARY KEY, start_time BIGINT NOT NULL UNIQUE, end_time BIGINT NOT NULL,
 status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','closed','reviewing','finalized')),
 reward_pool TEXT NOT NULL DEFAULT '0', finalized_at BIGINT, anti_fraud_version TEXT,
 CHECK(end_time=start_time+604800000), CHECK(round_id=start_time)
);
CREATE FUNCTION reputation_week(ms BIGINT) RETURNS BIGINT LANGUAGE SQL IMMUTABLE AS $$
 SELECT (floor((ms-345600000)::numeric/604800000)*604800000+345600000)::bigint
$$;
CREATE TABLE debate_votes (
 message_id BIGINT NOT NULL REFERENCES debate_messages(id), voter TEXT NOT NULL REFERENCES accounts(address),
 value BIGINT NOT NULL CHECK(value IN(-1,1)), awarded_at BIGINT NOT NULL,
 PRIMARY KEY(message_id,voter)
);
CREATE TABLE reputation_events (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 source TEXT NOT NULL CHECK(source IN('qa','debate','best')),
 target_id BIGINT NOT NULL, question_id TEXT NOT NULL, voter TEXT NOT NULL, recipient TEXT NOT NULL,
 previous_value BIGINT NOT NULL, value BIGINT NOT NULL, units BIGINT NOT NULL,
 occurred_at BIGINT NOT NULL, round_id BIGINT NOT NULL REFERENCES weekly_rounds(round_id),
 origin TEXT NOT NULL DEFAULT 'live' CHECK(origin IN('live','legacy_snapshot')),
 reason TEXT NOT NULL DEFAULT 'vote', rule_version TEXT NOT NULL DEFAULT 'reputation-v1', CHECK(voter<>recipient)
);
CREATE UNIQUE INDEX reputation_best_once ON reputation_events(question_id) WHERE source='best';
CREATE INDEX reputation_recipient_round ON reputation_events(recipient,round_id);
CREATE INDEX reputation_round ON reputation_events(round_id,id);
CREATE INDEX reputation_voter ON reputation_events(voter,occurred_at);
CREATE INDEX reputation_target ON reputation_events(source,target_id,id);
CREATE TABLE reputation_event_categories (
 event_id BIGINT NOT NULL REFERENCES reputation_events(id), category_id BIGINT NOT NULL REFERENCES categories(id),
 units BIGINT NOT NULL, PRIMARY KEY(event_id,category_id)
);
CREATE INDEX reputation_category ON reputation_event_categories(category_id,event_id);
-- Review data is deliberately separate from immutable visible score history.
-- NULL means not assessed, never a promise of reward eligibility.
CREATE TABLE reputation_reviews (
 event_id BIGINT PRIMARY KEY REFERENCES reputation_events(id), qualified_for_rewards BOOLEAN,
 trust_score INTEGER CHECK(trust_score BETWEEN 0 AND 100), fraud_reason TEXT, rule_version TEXT,
 review_status TEXT NOT NULL DEFAULT 'Watch' CHECK(review_status IN('Clean','Watch','Suspicious','Rejected','Manually Approved')),
 reviewed_at BIGINT, reviewed_by TEXT
);
CREATE TABLE reputation_account_reviews (
 address TEXT PRIMARY KEY REFERENCES accounts(address), qualified_for_rewards BOOLEAN,
 trust_score INTEGER CHECK(trust_score BETWEEN 0 AND 100), fraud_reason TEXT, rule_version TEXT,
 review_status TEXT NOT NULL DEFAULT 'Watch' CHECK(review_status IN('Clean','Watch','Suspicious','Rejected','Manually Approved')),
 reviewed_at BIGINT, reviewed_by TEXT
);
CREATE FUNCTION record_reputation(src TEXT,target BIGINT,qid TEXT,actor TEXT,beneficiary TEXT,oldval BIGINT,newval BIGINT,weight BIGINT,stamp BIGINT,provenance TEXT DEFAULT 'live',event_reason TEXT DEFAULT 'vote') RETURNS VOID LANGUAGE plpgsql AS $$
 DECLARE eid BIGINT; wk BIGINT; cnt BIGINT; cat RECORD;
 BEGIN
  IF actor=beneficiary OR oldval=newval THEN RETURN; END IF;
  wk:=reputation_week(stamp);
  INSERT INTO weekly_rounds(round_id,start_time,end_time) VALUES(wk,wk,wk+604800000) ON CONFLICT DO NOTHING;
  INSERT INTO reputation_events(source,target_id,question_id,voter,recipient,previous_value,value,units,occurred_at,round_id,origin,reason)
   VALUES(src,target,qid,actor,beneficiary,oldval,newval,(newval-oldval)*weight,stamp,wk,provenance,CASE WHEN src='best' THEN 'author_acceptance' ELSE event_reason END) RETURNING id INTO eid;
  SELECT count(*) INTO cnt FROM question_categories WHERE question_id=qid;
  -- Split each vote's total deterministically, including leftover hundredths.
  -- Difference of allocations makes vote changes/removals exactly reversible.
  FOR cat IN SELECT category_id,row_number() OVER(ORDER BY category_id) AS pos FROM question_categories WHERE question_id=qid LOOP
   INSERT INTO reputation_event_categories VALUES(eid,cat.category_id,(newval-oldval)*(weight/cnt+CASE WHEN cat.pos<=weight%cnt THEN 1 ELSE 0 END));
  END LOOP;
 END
$$;
CREATE FUNCTION reputation_vote_change() RETURNS trigger LANGUAGE plpgsql AS $$
 DECLARE src TEXT; target BIGINT; qid TEXT; beneficiary TEXT; actor TEXT; stamp BIGINT; oldval BIGINT:=0; newval BIGINT:=0; weight BIGINT;
 BEGIN
  IF TG_OP<>'INSERT' THEN oldval:=OLD.value; END IF;
  IF TG_OP<>'DELETE' THEN newval:=NEW.value; END IF;
  IF oldval=newval THEN RETURN NULL; END IF;
  IF TG_TABLE_NAME='reply_votes' THEN
   src:='qa'; weight:=100;
   IF TG_OP='DELETE' THEN target:=OLD.reply_id; actor:=OLD.voter; ELSE target:=NEW.reply_id; actor:=NEW.voter; END IF;
   SELECT question_id,author INTO qid,beneficiary FROM replies WHERE id=target;
  ELSE
   src:='debate'; weight:=25;
   IF TG_OP='DELETE' THEN target:=OLD.message_id; actor:=OLD.voter; ELSE target:=NEW.message_id; actor:=NEW.voter; END IF;
   SELECT question_id,author INTO qid,beneficiary FROM debate_messages WHERE id=target;
  END IF;
  IF actor=beneficiary THEN RAISE EXCEPTION 'Self-voting is not allowed'; END IF;
  stamp:=COALESCE(NULLIF(current_setting('neuron.event_time',true),'' )::bigint,(extract(epoch FROM clock_timestamp())*1000)::bigint);
  IF TG_OP<>'DELETE' THEN stamp:=NEW.awarded_at; END IF;
  PERFORM record_reputation(src,target,qid,actor,beneficiary,oldval,newval,weight,stamp);
  RETURN NULL;
 END
$$;
CREATE TRIGGER reply_reputation AFTER INSERT OR UPDATE OR DELETE ON reply_votes FOR EACH ROW EXECUTE FUNCTION reputation_vote_change();
CREATE TRIGGER debate_reputation AFTER INSERT OR UPDATE OR DELETE ON debate_votes FOR EACH ROW EXECUTE FUNCTION reputation_vote_change();
CREATE FUNCTION reputation_best_answer() RETURNS trigger LANGUAGE plpgsql AS $$
 BEGIN
  IF NEW.selection='author' AND NEW.answer_author IS NOT NULL THEN
   PERFORM record_reputation('best',NEW.reply_id,NEW.question_id,NEW.question_author,NEW.answer_author,0,1,500,NEW.closed_at);
  END IF;
  RETURN NULL;
 END
$$;
CREATE TRIGGER accepted_reputation AFTER INSERT ON accepted_answers FOR EACH ROW EXECUTE FUNCTION reputation_best_answer();
-- Existing votes become explicitly labelled snapshots, not fabricated full history.
SELECT record_reputation('qa',v.reply_id,r.question_id,v.voter,r.author,0,v.value,100,
 CASE WHEN v.awarded_at>0 THEN v.awarded_at ELSE r.created_at END,'legacy_snapshot')
 FROM reply_votes v JOIN replies r ON r.id=v.reply_id ORDER BY v.reply_id,v.voter;
SELECT record_reputation('best',a.reply_id,a.question_id,a.question_author,a.answer_author,0,1,500,a.closed_at,'legacy_snapshot')
 FROM accepted_answers a WHERE selection='author' AND answer_author IS NOT NULL ORDER BY closed_at,question_id;
-- Moderation keeps the visible votes but suspends their score. Restore is an
-- explicit compensating event, never removal or rewriting of prior history.
CREATE FUNCTION record_question_moderation(qid TEXT,hidden BOOLEAN,stamp BIGINT,provenance TEXT DEFAULT 'live') RETURNS VOID LANGUAGE plpgsql AS $$
 DECLARE entry RECORD;
 BEGIN
  FOR entry IN SELECT 'qa' AS src,r.id AS target,r.author,v.voter,v.value,100::bigint AS weight FROM reply_votes v JOIN replies r ON r.id=v.reply_id WHERE r.question_id=qid AND r.deleted_at IS NULL
   UNION ALL SELECT 'debate',m.id,m.author,v.voter,v.value,25::bigint FROM debate_votes v JOIN debate_messages m ON m.id=v.message_id WHERE m.question_id=qid LOOP
   PERFORM record_reputation(entry.src,entry.target,qid,entry.voter,entry.author,CASE WHEN hidden THEN entry.value ELSE 0 END,CASE WHEN hidden THEN 0 ELSE entry.value END,entry.weight,stamp,provenance,CASE WHEN hidden THEN 'moderation_hide' ELSE 'moderation_restore' END);
  END LOOP;
 END
$$;
CREATE FUNCTION reputation_moderation_change() RETURNS trigger LANGUAGE plpgsql AS $$
 BEGIN
  IF (OLD.deleted_at IS NULL)<>(NEW.deleted_at IS NULL) THEN
   PERFORM record_question_moderation(NEW.id,NEW.deleted_at IS NOT NULL,COALESCE(NULLIF(current_setting('neuron.event_time',true),'')::bigint,NEW.deleted_at,(extract(epoch FROM clock_timestamp())*1000)::bigint));
  END IF;
  RETURN NULL;
 END
$$;
CREATE TRIGGER moderation_reputation AFTER UPDATE OF deleted_at ON questions FOR EACH ROW EXECUTE FUNCTION reputation_moderation_change();
SELECT record_question_moderation(id,true,deleted_at,'legacy_snapshot') FROM questions WHERE deleted_at IS NOT NULL;
-- Deleted legacy replies can still have ratings; retain and offset the snapshot.
SELECT record_reputation('qa',v.reply_id,r.question_id,v.voter,r.author,v.value,0,100,r.deleted_at,'legacy_snapshot','answer_deleted')
 FROM reply_votes v JOIN replies r ON r.id=v.reply_id WHERE r.deleted_at IS NOT NULL;
CREATE FUNCTION immutable_reputation_history() RETURNS trigger LANGUAGE plpgsql AS $$
 BEGIN RAISE EXCEPTION 'Reputation history is append-only'; END
$$;
CREATE TRIGGER protect_reputation_events BEFORE UPDATE OR DELETE ON reputation_events FOR EACH ROW EXECUTE FUNCTION immutable_reputation_history();
CREATE TRIGGER protect_reputation_categories BEFORE UPDATE OR DELETE ON reputation_event_categories FOR EACH ROW EXECUTE FUNCTION immutable_reputation_history();
